export const UBI_QUICKSWAP_URL = "https://quickswap.exchange/#/swap?inputCurrency=0xfe7ff8b5dfba93a9eab7aee447c3c72990052d93"
export const MATIC_BRIDGE_URL = "https://wallet.matic.network/"
export const POLYGONSCAN_URL = "https://polygonscan.com/"
export const UBIROLL_POLYGONSCAN_URL = "https://polygonscan.com/address/0x84a5047e5d8eb5d009b0189e41256c9d6613a847"
export const UBIGAMES_GITHUB_URL = "https://github.com/shenwilly/ubi-games"
export const UBIROLL_GRAPH_ENDPOINT = "https://api.thegraph.com/subgraphs/name/shenwilly/ubiroll"
